/* ===================== GLOSSARY ===================== */
window.COURSE.glossary = [
  { term: 'Ab initio novation', def: 'A novation where the new party assumes ALL historic rights and liabilities, as if it had been a party from the beginning.', tags: ['novation'] },
  { term: 'Acceptance', def: 'Unconditional agreement by the offeree to the offeror\'s offer. A conditional acceptance is a counter‑offer; silence is not acceptance.', tags: ['formation'] },
  { term: 'Advance Payment Bond (APG)', def: 'A bank guarantee securing the advance payment; its value reduces as the advance is recovered from interim payments.', tags: ['securities','payment'] },
  { term: 'Ambiguity', def: 'Where the contract contains no information on a certain aspect; resolved by the Engineer issuing a clarification/instruction.', tags: ['documents'] },
  { term: 'Assignment', def: 'Transfer of the benefit (right) of a contract only — not the burden — often via collateral warranties.', tags: ['privity'] },
  { term: 'CAR (Contractor All Risk)', def: 'A non‑standard policy bundling material damage (Works) and third‑party liability cover.', tags: ['insurance'] },
  { term: 'Claim', def: 'A legitimate request for additional time and/or cost due to a change or breach of the contract.', tags: ['claims'] },
  { term: 'Collateral warranty', def: 'A device extending a duty of care / rights from a contracting party to a third party (tenant, funder, end‑user), overcoming privity.', tags: ['privity'] },
  { term: 'Consideration', def: 'The benefit (money or otherwise) given by the offeree in return for the offeror performing the offer.', tags: ['formation'] },
  { term: 'Contra proferentem', def: 'Rule that an ambiguity is construed against the party who drafted the clause.', tags: ['documents'] },
  { term: 'Contract Administration', def: 'Managing the contract AFTER signature — ensuring compliance and resolving issues during the project.', tags: ['competency'] },
  { term: 'Contract Practice', def: 'Preparing, drafting and understanding contracts BEFORE they are executed.', tags: ['competency'] },
  { term: 'Cross liability', def: 'Where co‑insured parties are treated as separately insured, so each can claim against the other under one policy.', tags: ['insurance'] },
  { term: 'DAAB', def: 'Dispute Avoidance/Adjudication Board — the FIDIC 2017 successor to the DAB.', tags: ['fidic','disputes'] },
  { term: 'DAB', def: 'Dispute Adjudication Board — introduced in FIDIC 1999 to adjudicate disputes.', tags: ['fidic','disputes'] },
  { term: 'Decennial liability', def: 'Implied‑by‑law liability (often 10 years) of contractor/architect for collapse or defects threatening stability; cannot be excluded (void).', tags: ['law'] },
  { term: 'Deductible', def: 'The amount of a loss not claimable from the insurer — used to avoid small claims.', tags: ['insurance'] },
  { term: 'Defects Liability / Notification Period (DLP/DNP)', def: 'Period (Cl 11, often ~12 months) during which the Contractor makes good defects; its end triggers the DLC and second‑half retention release.', tags: ['completion'] },
  { term: 'Determination', def: 'Mutual/agreed ending of a contract. (In FIDIC, also the Engineer\'s decision/opinion.)', tags: ['termination'] },
  { term: 'Discrepancy', def: 'Two different requirements stated for the same aspect; resolved via the priority of documents.', tags: ['documents'] },
  { term: 'Eichleay formula', def: 'A head‑office overhead recovery formula based on allocable overhead per day × days of compensable delay.', tags: ['delay'] },
  { term: 'Emden formula', def: 'HO overhead formula using an organisation‑wide overhead+profit ÷ turnover percentage.', tags: ['delay'] },
  { term: 'Ex gratia claim', def: 'A payment made out of goodwill/sympathy (e.g. exceptional fluctuations, COVID costs), not strict entitlement.', tags: ['claims'] },
  { term: 'Exceptional Events', def: 'FIDIC 2017 term consolidating Employer\'s Risks and Force Majeure.', tags: ['fidic'] },
  { term: 'Express terms', def: 'Terms specifically agreed by the parties.', tags: ['formation'] },
  { term: 'Force majeure', def: 'Unforeseeable events (war, disaster, pandemic) that prevent performance and may excuse the parties (Art 273).', tags: ['risk'] },
  { term: 'Frustration', def: 'A doctrine cancelling a contract when unforeseen events make completion impossible, releasing both parties (Art 893).', tags: ['risk'] },
  { term: 'Hudson formula', def: 'An HO overhead formula using the tendered HO/P %; discouraged by the SCL Protocol.', tags: ['delay'] },
  { term: 'Implied terms', def: 'Terms not expressly stated but assumed enforceable under law (e.g. decennial liability).', tags: ['formation'] },
  { term: 'Incorporated terms', def: 'Terms brought in by notice or a course of dealing.', tags: ['formation'] },
  { term: 'Interim Payment Certificate (IPC)', def: 'The Engineer\'s certificate of amounts due, deducting retention, advance recovery and contra charges (excluding LDs).', tags: ['payment'] },
  { term: 'Letter of Acceptance (LOA)', def: 'The Employer\'s formal acceptance of the Contractor\'s offer — creates a binding contract.', tags: ['formation'] },
  { term: 'Letter of Intent (LOI)', def: 'An expression of intent to contract in future; generally no binding contract; work done under it is paid on quantum meruit.', tags: ['formation'] },
  { term: 'Liquidated & Ascertained Damages (LAD)', def: 'A genuine pre‑estimate of the Employer\'s loss, pre‑agreed and calculable — payable on the Contractor\'s late completion.', tags: ['completion'] },
  { term: 'Nominated Subcontractor (NSC)', def: 'A subcontractor selected by the Employer but contracting with the Main Contractor.', tags: ['subcontract'] },
  { term: 'Novation', def: 'Transfer of both benefit and burden — replacing a party and creating a new contract.', tags: ['privity'] },
  { term: 'Offer', def: 'An expression of willingness to contract on stated terms, made by the offeror to the offeree.', tags: ['formation'] },
  { term: 'Parent Company Guarantee (PCG)', def: 'A pledge from a parent company to complete the project if its subsidiary cannot.', tags: ['securities'] },
  { term: 'Partial possession', def: 'Employer taking use of a substantially complete part of the works, before or after completion.', tags: ['completion'] },
  { term: 'Performance Bond', def: 'A bank security (~10% of contract sum), unconditional & on demand, protecting the Employer against Contractor breach.', tags: ['securities'] },
  { term: 'Prevention principle', def: 'A party cannot enforce an obligation it has itself prevented; if the Employer causes delay it cannot enforce completion or levy LDs.', tags: ['delay'] },
  { term: 'Privity of contract', def: 'Only the parties to a contract may enforce its terms or claim for breach.', tags: ['privity'] },
  { term: 'Prolongation cost', def: 'The cost associated with an EOT — extended site preliminaries plus a share of head‑office overheads.', tags: ['delay'] },
  { term: 'Provisional Sum', def: 'An allowance for work not sufficiently defined to price, and/or that the Employer may or may not want (Cl 13.5).', tags: ['payment'] },
  { term: 'Quantum meruit', def: '"As much as earned" — a fair and reasonable amount for work done without an agreed price (e.g. under an LOI).', tags: ['payment'] },
  { term: 'Retention', def: 'Money withheld to incentivise defect rectification; released half at TOC, half at end of DLP.', tags: ['payment'] },
  { term: 'SBLC', def: 'Standby Letter of Credit — pays on presentation of documents, not on default; may not be truly on‑demand.', tags: ['securities'] },
  { term: 'Sectional completion', def: 'Completion of a section for which a separate Time for Completion is provided.', tags: ['completion'] },
  { term: 'Subrogation', def: 'The insurer\'s right, after paying, to pursue whoever caused the loss; removable by a waiver of subrogation.', tags: ['insurance'] },
  { term: 'Substantial completion', def: 'The point at which the Employer can take beneficial use of the works for their intended purpose.', tags: ['completion'] },
  { term: 'Switch novation', def: 'A novation where the new party assumes rights & liabilities only from the date of novation.', tags: ['novation'] },
  { term: 'Taking‑Over Certificate (TOC)', def: 'Certificate of substantial completion; starts the DLP, releases first‑half retention and ends LDs for that part.', tags: ['completion'] },
  { term: 'Time at large', def: 'No fixed completion date / no mechanism to extend time when the Employer delays; Contractor must finish in a reasonable time and LDs fall away.', tags: ['delay'] },
  { term: 'Unjust enrichment', def: 'Where one party is enriched at the expense of the other — prevented by paying quantum meruit.', tags: ['payment'] },
  { term: 'Vesting certificate', def: 'A document passing title in materials to the Employer regardless of location; weaker security than a bond.', tags: ['payment'] },
  { term: 'Waiver of subrogation', def: 'Removes the insurer\'s right to recover from the party responsible for the loss.', tags: ['insurance'] },
];
