/* ===================== QUIZ BANK ===================== */
window.COURSE.quiz = [
  { part: 1, q: 'What is the key difference between Contract Practice and Contract Administration?', options: ['Practice is post‑signature; Administration is pre‑signature', 'Practice is pre‑signature (drafting/understanding); Administration is post‑signature (managing the contract)', 'They are the same thing', 'Practice applies only to FIDIC; Administration only to JCT'], answer: 1, why: 'Contract Practice deals with the contract before execution; Contract Administration manages it after signature.' },
  { part: 1, q: 'Which is NOT one of the three ways a term enters a contract?', options: ['Express', 'Implied', 'Incorporated', 'Negotiated'], answer: 3, why: 'Terms are Express, Implied or Incorporated. "Negotiated" is not a category.' },
  { part: 1, q: 'A conditional acceptance of an offer is best described as a…', options: ['Binding contract', 'Counter‑offer', 'Consideration', 'Collateral warranty'], answer: 1, why: 'A conditional/qualified acceptance rejects the original offer and becomes a counter‑offer.' },
  { part: 1, q: 'Under FIDIC 1999, which clause requires the Engineer to act impartially?', options: ['Cl 2.1', 'Cl 4.2', 'Cl 3.5', 'Cl 14.6'], answer: 2, why: 'Cl 3.5 — the Engineer must make fair determinations / act impartially.' },
  { part: 1, q: 'When two documents give different requirements for the same item, this is a…', options: ['Ambiguity', 'Discrepancy', 'Frustration', 'Variation'], answer: 1, why: 'A discrepancy (two different requirements) is resolved by the priority of documents; an ambiguity is a gap.' },
  { part: 1, q: 'The contra proferentem rule resolves an ambiguity…', options: ['In favour of the drafter', 'Against the party who drafted the clause', 'By the toss of a coin', 'Always in favour of the Contractor'], answer: 1, why: 'An ambiguity is construed against the party that drafted it.' },

  { part: 2, q: 'A clause excluding the contractor\'s decennial liability is…', options: ['Valid if both parties agree', 'Void (mandatory provision)', 'Valid only under FIDIC 2017', 'Valid if notarised'], answer: 1, why: 'Decennial liability is a mandatory provision (Art 882) — any clause excluding/limiting it is void.' },
  { part: 2, q: 'Work executed under a Letter of Intent is typically paid on the basis of…', options: ['Liquidated damages', 'Quantum meruit', 'Retention', 'Advance payment'], answer: 1, why: 'Quantum meruit — a fair & reasonable amount — applies to work done under an LOI (Arts 888/889).' },
  { part: 2, q: 'Which FIDIC book is used for EPC / Turnkey projects?', options: ['Red Book', 'Yellow Book', 'Silver Book', 'Green Book'], answer: 2, why: 'The Silver Book is for EPC/Turnkey; Red = employer‑design, Yellow = plant/design‑build, Green = short form.' },
  { part: 2, q: 'Which mechanism transfers BOTH the benefit and the burden of a contract?', options: ['Assignment', 'Novation', 'Collateral warranty', 'Subrogation'], answer: 1, why: 'Novation transfers benefit and burden and creates a new contract; assignment transfers benefit only.' },
  { part: 2, q: 'A performance bond must generally be…', options: ['Conditional and on proof of default', 'Unconditional and on demand', 'Issued by the Contractor', 'Equal to 50% of the contract sum'], answer: 1, why: 'It must be unconditional and on demand (usually ~10%), so the Employer need not prove default.' },
  { part: 2, q: 'Which was introduced by FIDIC 1999 (vs 1987)?', options: ['DAAB', 'Exceptional Events', 'Dispute Adjudication Board (DAB)', 'Clause 21 for disputes'], answer: 2, why: 'FIDIC 1999 introduced the DAB. DAAB, Exceptional Events and Cl 21 are 2017 changes.' },

  { part: 3, q: 'Advance payment first appeared in which FIDIC editions?', options: ['1987 only', '1999 & 2017 (not 1987)', 'All editions', 'None'], answer: 1, why: 'Advance payment is addressed in FIDIC 1999 & 2017 but not 1987.' },
  { part: 3, q: 'An occurrence‑basis insurance policy is triggered by…', options: ['The date the claim is reported', 'The date of the incident', 'The policy renewal date', 'The date of the loss adjuster\'s visit'], answer: 1, why: 'Occurrence basis triggers on the incident date (covered even if claimed later); claims‑made triggers on report date.' },
  { part: 3, q: 'Which cover is required if the Contractor carries out design?', options: ['Workmen\'s compensation', 'Professional Indemnity', 'Plant & equipment', 'Third party'], answer: 1, why: 'Professional Indemnity (PI) covers design liability.' },
  { part: 3, q: 'A waiver of subrogation…', options: ['Gives the insurer extra rights', 'Removes the insurer\'s right to recover from the responsible party', 'Increases the premium', 'Is the same as a deductible'], answer: 1, why: 'It removes the insurer\'s right to pursue whoever caused the loss.' },
  { part: 3, q: 'In an IPC, which is EXCLUDED from the contra‑charge deductions?', options: ['Retention', 'Advance‑payment recovery', 'Liquidated Damages', 'Engineer\'s overtime'], answer: 2, why: 'LDs are excluded from IPC contra charges and handled separately.' },

  { part: 4, q: 'Materials off site are typically paid at what proportion, and by whose determination?', options: ['100% by the Contractor', '80% as determined by the Engineer', '50% by the Employer', '10% by the bank'], answer: 1, why: 'Around 80% of cost as determined by the Engineer, with extra off‑site safeguards.' },
  { part: 4, q: 'Under FIDIC, the first half of retention is released…', options: ['At the end of the DLP', 'At the Taking‑Over Certificate', 'At contract signature', 'On advance payment'], answer: 1, why: 'First half at the TOC, second half at expiry of the DNP.' },
  { part: 4, q: 'A variation changes the…', options: ['Contract, not the Works', 'Works, not the Contract', 'Law of the land', 'Insurance policy'], answer: 1, why: 'A variation changes the Works but not the Contract itself.' },
  { part: 4, q: 'The prevention principle means the Employer…', options: ['Can always levy LDs', 'Cannot enforce completion or levy LDs for a delay it caused', 'Must pay quantum meruit', 'Can terminate at will'], answer: 1, why: 'A party cannot enforce an obligation it prevented; the Employer can\'t levy LDs for its own delay.' },
  { part: 4, q: 'For "exceptionally adverse climatic conditions", the Contractor is entitled to…', options: ['EOT and cost', 'EOT only, not cost', 'Cost only', 'Neither'], answer: 1, why: 'Time only — the event is beyond both parties\' control, so each bears its own loss.' },
  { part: 4, q: 'The FIDIC 1999 initial EOT notice must be given within…', options: ['7 days', '14 days', '28 days of awareness', '84 days'], answer: 2, why: 'Initial notice within 28 days of awareness; particulars within 42 days.' },

  { part: 5, q: 'A subcontractor selected by the Employer but contracting with the Main Contractor is…', options: ['Domestic', 'Named', 'Nominated', 'Novated'], answer: 2, why: 'Nominated Subcontractor (NSC): chosen by the Employer, contracts with the Main Contractor.' },
  { part: 5, q: 'Issuing a Taking‑Over Certificate does NOT…', options: ['Start the DLP', 'Release the first half of retention', 'End LDs for that part', 'Increase the retention percentage'], answer: 3, why: 'A TOC starts the DLP, releases first‑half retention and ends LDs — it does not raise retention.' },
  { part: 5, q: 'Piling below an existing structure with unknown ground conditions is best priced as a…', options: ['Defined provisional sum', 'Undefined provisional sum', 'Prime cost sum only', 'Liquidated sum'], answer: 1, why: 'Its extent can\'t be known in advance, so it is an undefined provisional sum under NRM.' },
  { part: 5, q: 'For which Employer‑termination grounds is termination immediate (no 14‑day notice)?', options: ['Slow progress', 'Insolvency and bribery', 'Late programme', 'Minor defects'], answer: 1, why: 'Grounds (e) insolvency and (f) bribery allow immediate termination (Cl 15.2).' },
  { part: 5, q: 'Prolonged suspension under FIDIC is typically one lasting more than…', options: ['28 days', '42 days', '56 days', '84 days'], answer: 3, why: '>84 days is a prolonged suspension (Cl 8.11 / 16.2).' },
  { part: 5, q: 'Liquidated & Ascertained Damages are…', options: ['Assessed on actual loss after the event', 'A genuine pre‑estimate of loss, set before the contract', 'A penalty designed to punish', 'The same as retention'], answer: 1, why: 'LADs are a genuine pre‑estimate, pre‑agreed and calculable; a penalty risks being unenforceable.' },
  { part: 5, q: 'Force majeure and frustration both concern events that are…', options: ['Within a party\'s control', 'Beyond the parties\' control', 'Always insurable', 'Only financial'], answer: 1, why: 'Both deal with events beyond the parties\' control; FM excuses/suspends, frustration ends the contract.' },
];
